import numpy as np
import matplotlib.pyplot as plt
epochs=list(range(1,11))
loss=np.array([0.2,0.5,0.8,0.9,0.23,0.65,0.61,0.23,0.11,0.08])
plt.figure(figsize=(8,5))
plt.plot(loss,epochs,marker="s")
plt.xlabel("loss")
plt.ylabel("epochs")
plt.title("loss vs epochs")
plt.grid(True)
plt.show()
plt.figure()
plt.scatter(epochs,loss)
plt.xlabel("epochs")
plt.ylabel("loss")
plt.title("epochs vs loss")
plt.grid(True)
plt.show()
plt.figure()
plt.bar(["Model A","Model B","Model C"],[0.85,0.9,0.88])
plt.xlabel("Different Models")
plt.ylabel("Accuracy")
plt.title("accuracy of different models")

plt.grid(True)
plt.show()